# Uncomment the next line to define a global platform for your project
  platform :ios, '13.0'

target 'SwiftProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for SwiftProject
    pod 'Alamofire'
    pod 'Kingfisher'
    pod 'RxSwift'
    pod 'NSObject+Rx'
    pod 'RxDataSources'
    pod 'RxCocoa'
    pod 'Moya/RxSwift'
    pod 'Result'
    pod 'HandyJSON'
    pod 'SnapKit'
    pod "IQKeyboardManagerSwift"
    pod 'JXPhotoBrowser'
    pod 'HBDNavigationBar'
    
    
    #
end
